app:
  mode: debug

server:
  port: 8090

database:
  type: "mysql"
  user: "root"
  password:
  port: 3306
  dbname: "my_blog"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  port: 6379
  db: 0
  password: ""

