app:
  mode: debug
  page_size: 10

server:
  port: 8090
  read_timeout: 60
  write_timeout: 60

database:
  type: "mysql"
  user: "root"
  password: ""
  port: 3306
  dbname: "my_blog"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  port: 6379
  db: 0
  password: ""

